/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.view.panel.crud;

import br.controller.ControllerPanelCRUD;
import br.view.SubPanel;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;

/**
 *
 * @author vinic
 */
public class PanelCRUD extends SubPanel {

    private ControllerPanelCRUD controller;
    
    public ControllerPanelCRUD getController() {
        return this.controller;
    }
    
    /**
     * Creates new form PanelCRUD
     */
    public PanelCRUD() {
        initComponents();
        this.controller = new ControllerPanelCRUD();
        this.controller.setView(this);
        this.controller.trocaTela(new PanelCadastroUsuarios());
        this.bg_usuarios.add(rb_vizualizar);
        this.bg_usuarios.add(tb_cadastrar);
        this.tb_cadastrar.setSelected(true);
        //System.out.println(this.pn_usuarios.getWidth() + "x" + this.pn_usuarios.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_usuarios = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        rb_vizualizar = new javax.swing.JRadioButton();
        tb_cadastrar = new javax.swing.JRadioButton();
        pn_usuarios = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        rb_vizualizar.setText("Vizualizar Todos os Usuários Cadastrados");
        rb_vizualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_vizualizarActionPerformed(evt);
            }
        });

        tb_cadastrar.setText("Cadastrar Usuário");
        tb_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_cadastrarActionPerformed(evt);
            }
        });

        pn_usuarios.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(178, Short.MAX_VALUE)
                .addComponent(tb_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_vizualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addGap(152, 152, 152))
            .addComponent(pn_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_vizualizar)
                    .addComponent(tb_cadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuários", jPanel3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Produtos", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Fornecedores", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rb_vizualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_vizualizarActionPerformed
        this.controller.trocaTela(new PanelVizualizarUsuarios());
    }//GEN-LAST:event_rb_vizualizarActionPerformed

    private void tb_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_cadastrarActionPerformed
        this.controller.trocaTela(new PanelCadastroUsuarios());
    }//GEN-LAST:event_tb_cadastrarActionPerformed

    public ButtonGroup getBg_usuarios() {
        return bg_usuarios;
    }

    public void setBg_usuarios(ButtonGroup bg_usuarios) {
        this.bg_usuarios = bg_usuarios;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    public void setjPanel5(JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    public JPanel getjPanel6() {
        return jPanel6;
    }

    public void setjPanel6(JPanel jPanel6) {
        this.jPanel6 = jPanel6;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JPanel getPn_usuarios() {
        return pn_usuarios;
    }

    public void setPn_usuarios(JPanel pn_usuarios) {
        this.pn_usuarios = pn_usuarios;
    }

    public JRadioButton getRb_vizualizar() {
        return rb_vizualizar;
    }

    public void setRb_vizualizar(JRadioButton rb_vizualizar) {
        this.rb_vizualizar = rb_vizualizar;
    }

    public JRadioButton getTb_cadastrar() {
        return tb_cadastrar;
    }

    public void setTb_cadastrar(JRadioButton tb_cadastrar) {
        this.tb_cadastrar = tb_cadastrar;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_usuarios;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pn_usuarios;
    private javax.swing.JRadioButton rb_vizualizar;
    private javax.swing.JRadioButton tb_cadastrar;
    // End of variables declaration//GEN-END:variables
}
