/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.view;

import br.controller.ControllerPrincipal;
import br.util.Imagens;
import br.view.panel.funcionario.PanelFuncionario;
import br.view.panel.historico.PanelHistorico;
import br.view.panel.crud.PanelCRUD;
import br.view.panel.financeiro.PanelFinanceiro;
import br.view.panel.principal.PanelPrincipal;
import br.view.panel.vendas.PanelVendas;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author 104884
 */
public class FramePrincipal extends javax.swing.JFrame {

    private ControllerPrincipal controller;
    
    public ControllerPrincipal getController() {
        return this.controller;
    }
    /**
     * Creates new form Principal
     */
    public FramePrincipal() {
        initComponents();
        this.controller = new ControllerPrincipal();
        this.controller.setView(this);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setMinimumSize(new Dimension(this.getWidth(), this.getHeight()));
        this.jPanel2.add(new PanelPrincipal());
        this.jPanel2.repaint();
        this.jPanel2.revalidate();
        this.controller.prepararBotoes(Imagens.ICON_PRINCIPAL, this.btn_principal);
        this.controller.prepararBotoes(Imagens.ICON_USUARIO, this.btn_funcionario);
        this.controller.prepararBotoes(Imagens.ICON_VENDAS, this.btn_vendas);
        this.controller.prepararBotoes(Imagens.ICON_FINANCEIRO, this.btn_financeiro);
        this.controller.prepararBotoes(Imagens.ICON_DATABASE, this.btn_crud);
        this.controller.prepararBotoes(Imagens.ICON_HISTORICO, this.btn_historico);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_principal = new javax.swing.JButton();
        btn_vendas = new javax.swing.JButton();
        btn_funcionario = new javax.swing.JButton();
        btn_financeiro = new javax.swing.JButton();
        btn_crud = new javax.swing.JButton();
        btn_historico = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_principal.setText("Principal");
        btn_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_principalActionPerformed(evt);
            }
        });

        btn_vendas.setText("Vendas");
        btn_vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vendasActionPerformed(evt);
            }
        });

        btn_funcionario.setText("Usuário");
        btn_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_funcionarioActionPerformed(evt);
            }
        });

        btn_financeiro.setText("Financeiro");
        btn_financeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_financeiroActionPerformed(evt);
            }
        });

        btn_crud.setText("Cadastros");
        btn_crud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crudActionPerformed(evt);
            }
        });

        btn_historico.setText("Historico");
        btn_historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_principal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_funcionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_vendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_financeiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_crud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_historico)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_principal)
                    .addComponent(btn_vendas)
                    .addComponent(btn_funcionario)
                    .addComponent(btn_financeiro)
                    .addComponent(btn_crud)
                    .addComponent(btn_historico))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_principalActionPerformed
        this.controller.trocaTela(new PanelPrincipal());
    }//GEN-LAST:event_btn_principalActionPerformed

    private void btn_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_funcionarioActionPerformed
        this.controller.trocaTela(new PanelFuncionario());
    }//GEN-LAST:event_btn_funcionarioActionPerformed

    private void btn_vendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vendasActionPerformed
        this.controller.trocaTela(new PanelVendas());
    }//GEN-LAST:event_btn_vendasActionPerformed

    private void btn_financeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_financeiroActionPerformed
        this.controller.trocaTela(new PanelFinanceiro());
    }//GEN-LAST:event_btn_financeiroActionPerformed

    private void btn_crudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crudActionPerformed
        this.controller.trocaTela(new PanelCRUD());
    }//GEN-LAST:event_btn_crudActionPerformed

    private void btn_historicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historicoActionPerformed
        this.controller.trocaTela(new PanelHistorico());
    }//GEN-LAST:event_btn_historicoActionPerformed

    public JButton getjButton1() {
        return btn_principal;
    }

    public JButton getjButton2() {
        return btn_vendas;
    }

    public JButton getjButton3() {
        return btn_funcionario;
    }

    public JButton getjButton4() {
        return btn_financeiro;
    }

    public JButton getjButton5() {
        return btn_crud;
    }

    public JButton getjButton6() {
        return btn_historico;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_crud;
    private javax.swing.JButton btn_financeiro;
    private javax.swing.JButton btn_funcionario;
    private javax.swing.JButton btn_historico;
    private javax.swing.JButton btn_principal;
    private javax.swing.JButton btn_vendas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
