/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.view;

import br.controller.ControllerPanelCRUD;
import br.view.SubPanel;
import java.awt.event.KeyEvent;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author vinic
 */
public class PanelCRUD extends SubPanel {

    private ControllerPanelCRUD controller;
    
    public ControllerPanelCRUD getController() {
        return this.controller;
    }
    
    /**
     * Creates new form PanelCRUD
     */
    public PanelCRUD() {
        initComponents();
        this.controller = new ControllerPanelCRUD();
        this.controller.setView(this);
        this.controller.iniciaTabelaUsuarios();
        this.controller.iniciaTabelaProdutos();
        this.cb_pergunta.addItem("");
        this.controller.trocaMask();
        ((JLabel)this.cb_codigo.getRenderer()).setHorizontalAlignment(SwingConstants.RIGHT);
        ((JLabel)this.cb_tipoProduto.getRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        ((JLabel)this.cb_tipoUsuario.getRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_usuarios = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_usuarios = new javax.swing.JTable();
        tf_pesquisa = new javax.swing.JTextField();
        pn_cadastroUsuarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        cb_tipoUsuario = new javax.swing.JComboBox<>();
        cb_codigo = new javax.swing.JComboBox<>();
        tf_codigo = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_salario = new javax.swing.JFormattedTextField();
        tf_nomeUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_senha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        tf_confirmaSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        cb_pergunta = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tf_resposta = new javax.swing.JTextField();
        btn_cadastrarUsuario = new javax.swing.JButton();
        btn_redefinirUsuario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tf_pesquisaProdutos = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_produtos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cb_tipoProduto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tf_nomeProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tf_precoCompra = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        tf_precoVenda = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        tf_quantidade = new javax.swing.JFormattedTextField();
        btn_cadastrarProduto = new javax.swing.JButton();
        btn_redefinirProduto = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tf_validade = new javax.swing.JFormattedTextField();

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });

        tb_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome de Usuário", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_usuariosMouseClicked(evt);
            }
        });
        tb_usuarios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_usuariosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_usuarios);

        tf_pesquisa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_pesquisaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                    .addComponent(tf_pesquisa))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vizualizar Usuários", jPanel1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nome");

        cb_tipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Funcionário", "Caixa" }));
        cb_tipoUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipoUsuarioItemStateChanged(evt);
            }
        });

        cb_codigo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPF", "CNPJ" }));
        cb_codigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_codigoItemStateChanged(evt);
            }
        });

        tf_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome de Usuário");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Salário");

        tf_salario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tf_salario.setEnabled(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Senha");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Confirmar Senha");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Pergunta");

        cb_pergunta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qual é o nome do seu melhor amigo de infância?", "Qual o nome do hospital em que você nasceu?", "Qual era o nome do seu primeiro animal de estimação?", "Qual o destino da sua primeira viagem de avião?", "Qual era o nome do seu professor favorito no entra-21?" }));
        cb_pergunta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_perguntaItemStateChanged(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Resposta");

        btn_cadastrarUsuario.setText("Cadastrar Usuário");
        btn_cadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarUsuarioActionPerformed(evt);
            }
        });

        btn_redefinirUsuario.setText("Redefinir");
        btn_redefinirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_redefinirUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_cadastroUsuariosLayout = new javax.swing.GroupLayout(pn_cadastroUsuarios);
        pn_cadastroUsuarios.setLayout(pn_cadastroUsuariosLayout);
        pn_cadastroUsuariosLayout.setHorizontalGroup(
            pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cadastroUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_tipoUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pn_cadastroUsuariosLayout.createSequentialGroup()
                        .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_codigo, 0, 97, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_codigo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_salario)
                            .addComponent(tf_nome)))
                    .addGroup(pn_cadastroUsuariosLayout.createSequentialGroup()
                        .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_confirmaSenha)
                            .addComponent(tf_nomeUsuario)
                            .addComponent(tf_senha)
                            .addComponent(cb_pergunta, 0, 621, Short.MAX_VALUE)
                            .addComponent(tf_resposta)))
                    .addGroup(pn_cadastroUsuariosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cadastrarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_redefinirUsuario)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_cadastroUsuariosLayout.setVerticalGroup(
            pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cadastroUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_tipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_pergunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_resposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_cadastroUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrarUsuario)
                    .addComponent(btn_redefinirUsuario))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Usuários", pn_cadastroUsuarios);

        tf_pesquisaProdutos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_pesquisaProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_pesquisaProdutosKeyPressed(evt);
            }
        });

        tb_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Preço Compra", "Preço Venda", "Quantidade", "Data de Validade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_produtosMouseClicked(evt);
            }
        });
        tb_produtos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_produtosKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tb_produtos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_pesquisaProdutos)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_pesquisaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vizualizar Produtos", jPanel2);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Tipo de Produto");

        cb_tipoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidade", "Quilo" }));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Nome do Produto");

        jLabel10.setText("Preço de Compra");

        tf_precoCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Preço de Venda");

        tf_precoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Quantidade");

        tf_quantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        btn_cadastrarProduto.setText("Cadastrar Produto");
        btn_cadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarProdutoActionPerformed(evt);
            }
        });

        btn_redefinirProduto.setText("Redefinir");
        btn_redefinirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_redefinirProdutoActionPerformed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Validade");
        jLabel13.setToolTipText("");

        try {
            tf_validade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 251, Short.MAX_VALUE)
                        .addComponent(btn_cadastrarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_redefinirProduto)
                        .addContainerGap(257, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_nomeProduto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_precoCompra, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_precoVenda, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_quantidade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_validade)
                            .addComponent(cb_tipoProduto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_tipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_precoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_precoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_validade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_redefinirProduto)
                    .addComponent(btn_cadastrarProduto))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar Produtos", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_pesquisaProdutosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pesquisaProdutosKeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            this.controller.filtraTabelaProdutos();
        }
    }//GEN-LAST:event_tf_pesquisaProdutosKeyPressed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void btn_redefinirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_redefinirUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_redefinirUsuarioActionPerformed

    private void btn_cadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarUsuarioActionPerformed
        this.controller.cadastrarUsuario();
    }//GEN-LAST:event_btn_cadastrarUsuarioActionPerformed

    private void tf_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_codigoActionPerformed

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained

    }//GEN-LAST:event_jPanel1FocusGained

    private void tf_pesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pesquisaKeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            this.controller.filtraTabelaUsuarios();
        }
    }//GEN-LAST:event_tf_pesquisaKeyPressed

    private void tb_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_usuariosMouseClicked
        if(evt.getClickCount() == 2) {
            this.controller.editarUsuarioSelecionado();
        }
    }//GEN-LAST:event_tb_usuariosMouseClicked

    private void cb_codigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_codigoItemStateChanged
        this.controller.trocaMask();
    }//GEN-LAST:event_cb_codigoItemStateChanged

    private void cb_tipoUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipoUsuarioItemStateChanged
        this.controller.cb_tipoUsuarioItemStateChanged();
    }//GEN-LAST:event_cb_tipoUsuarioItemStateChanged

    private void cb_perguntaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_perguntaItemStateChanged
        this.controller.cb_pergunta_itemStateChanged();
    }//GEN-LAST:event_cb_perguntaItemStateChanged

    private void tb_usuariosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_usuariosKeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_DELETE) {
            this.controller.excluirUsuarioSelecionado();
        }
    }//GEN-LAST:event_tb_usuariosKeyPressed

    private void btn_cadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarProdutoActionPerformed
        this.controller.cadastrarProduto();
    }//GEN-LAST:event_btn_cadastrarProdutoActionPerformed

    private void btn_redefinirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_redefinirProdutoActionPerformed
        this.controller.redefinirFormProduto();
    }//GEN-LAST:event_btn_redefinirProdutoActionPerformed

    private void tb_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_produtosMouseClicked
        if(evt.getClickCount() == 2) {
            this.controller.editarProdutoSelecionado();
        }
    }//GEN-LAST:event_tb_produtosMouseClicked

    private void tb_produtosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_produtosKeyPressed
        if(evt.getKeyChar() == KeyEvent.VK_DELETE) {
            this.controller.excluirProdutoSelecionado();
        }
    }//GEN-LAST:event_tb_produtosKeyPressed

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JFormattedTextField getTf_validade() {
        return tf_validade;
    }

    public void setTf_validade(JFormattedTextField tf_validade) {
        this.tf_validade = tf_validade;
    }

    public ButtonGroup getBg_usuarios() {
        return bg_usuarios;
    }

    public void setBg_usuarios(ButtonGroup bg_usuarios) {
        this.bg_usuarios = bg_usuarios;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    public void setjPanel5(JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }

    public JComboBox<String> getCb_tipoProduto() {
        return cb_tipoProduto;
    }

    public void setCb_tipoProduto(JComboBox<String> cb_tipoProduto) {
        this.cb_tipoProduto = cb_tipoProduto;
    }

    public JButton getjButton1() {
        return btn_cadastrarUsuario;
    }

    public void setjButton1(JButton jButton1) {
        this.btn_cadastrarUsuario = jButton1;
    }

    public JButton getjButton2() {
        return btn_redefinirUsuario;
    }

    public void setjButton2(JButton jButton2) {
        this.btn_redefinirUsuario = jButton2;
    }

    public JButton getjButton3() {
        return btn_cadastrarProduto;
    }

    public void setjButton3(JButton jButton3) {
        this.btn_cadastrarProduto = jButton3;
    }

    public JButton getjButton4() {
        return btn_redefinirProduto;
    }

    public void setjButton4(JButton jButton4) {
        this.btn_redefinirProduto = jButton4;
    }

    public JComboBox<String> getjComboBox1() {
        return cb_tipoUsuario;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.cb_tipoUsuario = jComboBox1;
    }

    public JButton getBtn_cadastrarProduto() {
        return btn_cadastrarProduto;
    }

    public void setBtn_cadastrarProduto(JButton btn_cadastrarProduto) {
        this.btn_cadastrarProduto = btn_cadastrarProduto;
    }

    public JButton getBtn_redefinirProduto() {
        return btn_redefinirProduto;
    }

    public void setBtn_redefinirProduto(JButton btn_redefinirProduto) {
        this.btn_redefinirProduto = btn_redefinirProduto;
    }

    public JComboBox<String> getjComboBox2() {
        return cb_codigo;
    }

    public void setjComboBox2(JComboBox<String> jComboBox2) {
        this.cb_codigo = jComboBox2;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public void setjLabel9(JLabel jLabel9) {
        this.jLabel9 = jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JPanel getPn_cadastroUsuarios() {
        return pn_cadastroUsuarios;
    }

    public void setPn_cadastroUsuarios(JPanel pn_cadastroUsuarios) {
        this.pn_cadastroUsuarios = pn_cadastroUsuarios;
    }

    public JTable getTb_usuarios() {
        return tb_usuarios;
    }

    public void setTb_usuarios(JTable tb_usuarios) {
        this.tb_usuarios = tb_usuarios;
    }

    public JFormattedTextField getTf_codigo() {
        return tf_codigo;
    }

    public void setTf_codigo(JFormattedTextField tf_codigo) {
        this.tf_codigo = tf_codigo;
    }

    public JPasswordField getTf_confirmaSenha() {
        return tf_confirmaSenha;
    }

    public void setTf_confirmaSenha(JPasswordField tf_confirmaSenha) {
        this.tf_confirmaSenha = tf_confirmaSenha;
    }

    public JTextField getTf_nome() {
        return tf_nome;
    }

    public void setTf_nome(JTextField tf_nome) {
        this.tf_nome = tf_nome;
    }

    public JTextField getTf_nomeProduto() {
        return tf_nomeProduto;
    }

    public void setTf_nomeProduto(JTextField tf_nomeProduto) {
        this.tf_nomeProduto = tf_nomeProduto;
    }

    public JTextField getTf_nomeUsuario() {
        return tf_nomeUsuario;
    }

    public void setTf_nomeUsuario(JTextField tf_nomeUsuario) {
        this.tf_nomeUsuario = tf_nomeUsuario;
    }

    public JComboBox<String> getTf_pergunta() {
        return cb_pergunta;
    }

    public void setTf_pergunta(JComboBox<String> tf_pergunta) {
        this.cb_pergunta = tf_pergunta;
    }

    public JTextField getTf_pesquisa() {
        return tf_pesquisa;
    }

    public void setTf_pesquisa(JTextField tf_pesquisa) {
        this.tf_pesquisa = tf_pesquisa;
    }

    public JFormattedTextField getTf_precoCompra() {
        return tf_precoCompra;
    }

    public void setTf_precoCompra(JFormattedTextField tf_precoCompra) {
        this.tf_precoCompra = tf_precoCompra;
    }

    public JFormattedTextField getTf_precoVenda() {
        return tf_precoVenda;
    }

    public void setTf_precoVenda(JFormattedTextField tf_precoVenda) {
        this.tf_precoVenda = tf_precoVenda;
    }

    public JFormattedTextField getTf_quantidade() {
        return tf_quantidade;
    }

    public void setTf_quantidade(JFormattedTextField tf_quantidade) {
        this.tf_quantidade = tf_quantidade;
    }

    public JTextField getTf_resposta() {
        return tf_resposta;
    }

    public void setTf_resposta(JTextField tf_resposta) {
        this.tf_resposta = tf_resposta;
    }

    public JFormattedTextField getTf_salario() {
        return tf_salario;
    }

    public void setTf_salario(JFormattedTextField tf_salario) {
        this.tf_salario = tf_salario;
    }

    public JPasswordField getTf_senha() {
        return tf_senha;
    }

    public void setTf_senha(JPasswordField tf_senha) {
        this.tf_senha = tf_senha;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTable getTb_produtos() {
        return tb_produtos;
    }

    public void setTb_produtos(JTable tb_produtos) {
        this.tb_produtos = tb_produtos;
    }

    public JTextField getTf_pesquisaProdutos() {
        return tf_pesquisaProdutos;
    }

    public void setTf_pesquisaProdutos(JTextField tf_pesquisaProdutos) {
        this.tf_pesquisaProdutos = tf_pesquisaProdutos;
    }

    public JComboBox<String> getCb_codigo() {
        return cb_codigo;
    }

    public void setCb_codigo(JComboBox<String> cb_codigo) {
        this.cb_codigo = cb_codigo;
    }

    public JComboBox<String> getCb_pergunta() {
        return cb_pergunta;
    }

    public void setCb_pergunta(JComboBox<String> cb_pergunta) {
        this.cb_pergunta = cb_pergunta;
    }

    public JComboBox<String> getCb_tipoUsuario() {
        return cb_tipoUsuario;
    }

    public void setCb_tipoUsuario(JComboBox<String> cb_tipoUsuario) {
        this.cb_tipoUsuario = cb_tipoUsuario;
    }

    public JButton getBtn_cadastrarUsuario() {
        return btn_cadastrarUsuario;
    }

    public void setBtn_cadastrarUsuario(JButton btn_cadastrarUsuario) {
        this.btn_cadastrarUsuario = btn_cadastrarUsuario;
    }

    public JButton getBtn_redefinirUsuario() {
        return btn_redefinirUsuario;
    }

    public void setBtn_redefinirUsuario(JButton btn_redefinirUsuario) {
        this.btn_redefinirUsuario = btn_redefinirUsuario;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_usuarios;
    private javax.swing.JButton btn_cadastrarProduto;
    private javax.swing.JButton btn_cadastrarUsuario;
    private javax.swing.JButton btn_redefinirProduto;
    private javax.swing.JButton btn_redefinirUsuario;
    private javax.swing.JComboBox<String> cb_codigo;
    private javax.swing.JComboBox<String> cb_pergunta;
    private javax.swing.JComboBox<String> cb_tipoProduto;
    private javax.swing.JComboBox<String> cb_tipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pn_cadastroUsuarios;
    private javax.swing.JTable tb_produtos;
    private javax.swing.JTable tb_usuarios;
    private javax.swing.JFormattedTextField tf_codigo;
    private javax.swing.JPasswordField tf_confirmaSenha;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_nomeProduto;
    private javax.swing.JTextField tf_nomeUsuario;
    private javax.swing.JTextField tf_pesquisa;
    private javax.swing.JTextField tf_pesquisaProdutos;
    private javax.swing.JFormattedTextField tf_precoCompra;
    private javax.swing.JFormattedTextField tf_precoVenda;
    private javax.swing.JFormattedTextField tf_quantidade;
    private javax.swing.JTextField tf_resposta;
    private javax.swing.JFormattedTextField tf_salario;
    private javax.swing.JPasswordField tf_senha;
    private javax.swing.JFormattedTextField tf_validade;
    // End of variables declaration//GEN-END:variables
}
